python-buildpack/python_buildpack-cflinuxfs4-v1.8.42.zip:
  size: 6039759
  object_id: d3446c34-b52b-4b1c-605f-7486672a3c60
  sha: sha256:f7672816d35fc17ef8d2ff6f57b78b78d785db5bc5eefa79f8757447737a690c
