python-buildpack/python_buildpack-cflinuxfs4-v1.8.41.zip:
  size: 6039726
  object_id: dcda4b50-f825-4526-5557-37f092c4b6be
  sha: sha256:794e04c5a486c23f4cbd625dec5502b8f0b29673f22f59b0d590a6432ba3537d
